/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Assignment = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'dueDate' : Time,
  'updatedAt' : Time,
  'notes' : IDL.Opt(IDL.Text),
  'priority' : Priority,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'total' : IDL.Nat,
  'pending' : IDL.Nat,
  'completed' : IDL.Nat,
  'overdue' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAssignment' : IDL.Func(
      [IDL.Text, IDL.Text, Time, Priority, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deleteAssignment' : IDL.Func([IDL.Nat], [], []),
  'filterByStatus' : IDL.Func([Status], [IDL.Vec(Assignment)], ['query']),
  'filterBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Assignment)], ['query']),
  'getAIStudyTips' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
  'getAssignment' : IDL.Func([IDL.Nat], [Assignment], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getUniqueStatuses' : IDL.Func([], [IDL.Vec(Status)], ['query']),
  'getUniqueSubjects' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSeedData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAssignmentComplete' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAssignment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, Time, Priority, Status, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Assignment = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'dueDate' : Time,
    'updatedAt' : Time,
    'notes' : IDL.Opt(IDL.Text),
    'priority' : Priority,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'total' : IDL.Nat,
    'pending' : IDL.Nat,
    'completed' : IDL.Nat,
    'overdue' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAssignment' : IDL.Func(
        [IDL.Text, IDL.Text, Time, Priority, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'deleteAssignment' : IDL.Func([IDL.Nat], [], []),
    'filterByStatus' : IDL.Func([Status], [IDL.Vec(Assignment)], ['query']),
    'filterBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Assignment)], ['query']),
    'getAIStudyTips' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
    'getAssignment' : IDL.Func([IDL.Nat], [Assignment], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getUniqueStatuses' : IDL.Func([], [IDL.Vec(Status)], ['query']),
    'getUniqueSubjects' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSeedData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAssignmentComplete' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAssignment' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          Time,
          Priority,
          Status,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };