/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assignment {
  'id' : bigint,
  'status' : Status,
  'title' : string,
  'subject' : string,
  'owner' : Principal,
  'createdAt' : Time,
  'dueDate' : Time,
  'updatedAt' : Time,
  'notes' : [] | [string],
  'priority' : Priority,
}
export interface DashboardStats {
  'total' : bigint,
  'pending' : bigint,
  'completed' : bigint,
  'overdue' : bigint,
}
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type Status = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAssignment' : ActorMethod<
    [string, string, Time, Priority, [] | [string]],
    bigint
  >,
  'deleteAssignment' : ActorMethod<[bigint], undefined>,
  'filterByStatus' : ActorMethod<[Status], Array<Assignment>>,
  'filterBySubject' : ActorMethod<[string], Array<Assignment>>,
  'getAIStudyTips' : ActorMethod<[bigint], string>,
  'getAllAssignments' : ActorMethod<[], Array<Assignment>>,
  'getAssignment' : ActorMethod<[bigint], Assignment>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getUniqueStatuses' : ActorMethod<[], Array<Status>>,
  'getUniqueSubjects' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSeedData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAssignmentComplete' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAssignment' : ActorMethod<
    [bigint, string, string, Time, Priority, Status, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];