/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Assignment {
    id: bigint;
    status: Status;
    title: string;
    subject: string;
    owner: Principal;
    createdAt: Time;
    dueDate: Time;
    updatedAt: Time;
    notes?: string;
    priority: Priority;
}
export interface DashboardStats {
    total: bigint;
    pending: bigint;
    completed: bigint;
    overdue: bigint;
}
export interface UserProfile {
    name: string;
}
export enum Priority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum Status {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAssignment(title: string, subject: string, dueDate: Time, priority: Priority, notes: string | null): Promise<bigint>;
    deleteAssignment(id: bigint): Promise<void>;
    filterByStatus(status: Status): Promise<Array<Assignment>>;
    filterBySubject(subject: string): Promise<Array<Assignment>>;
    getAIStudyTips(id: bigint): Promise<string>;
    getAllAssignments(): Promise<Array<Assignment>>;
    getAssignment(id: bigint): Promise<Assignment>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getUniqueStatuses(): Promise<Array<Status>>;
    getUniqueSubjects(): Promise<Array<string>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeSeedData(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    markAssignmentComplete(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAssignment(id: bigint, title: string, subject: string, dueDate: Time, priority: Priority, status: Status, notes: string | null): Promise<void>;
}
import type { Assignment as _Assignment, Priority as _Priority, Status as _Status, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAssignment(arg0: string, arg1: string, arg2: Time, arg3: Priority, arg4: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssignment(arg0, arg1, arg2, to_candid_Priority_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssignment(arg0, arg1, arg2, to_candid_Priority_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async deleteAssignment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAssignment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAssignment(arg0);
            return result;
        }
    }
    async filterByStatus(arg0: Status): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterByStatus(to_candid_Status_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterByStatus(to_candid_Status_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterBySubject(arg0: string): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterBySubject(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterBySubject(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAIStudyTips(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAIStudyTips(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAIStudyTips(arg0);
            return result;
        }
    }
    async getAllAssignments(): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssignments();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssignments();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssignment(arg0: bigint): Promise<Assignment> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignment(arg0);
                return from_candid_Assignment_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignment(arg0);
            return from_candid_Assignment_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getUniqueStatuses(): Promise<Array<Status>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUniqueStatuses();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUniqueStatuses();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUniqueSubjects(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUniqueSubjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUniqueSubjects();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeSeedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeSeedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeSeedData();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAssignmentComplete(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAssignmentComplete(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAssignmentComplete(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateAssignment(arg0: bigint, arg1: string, arg2: string, arg3: Time, arg4: Priority, arg5: Status, arg6: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssignment(arg0, arg1, arg2, arg3, to_candid_Priority_n3(this._uploadFile, this._downloadFile, arg4), to_candid_Status_n6(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssignment(arg0, arg1, arg2, arg3, to_candid_Priority_n3(this._uploadFile, this._downloadFile, arg4), to_candid_Status_n6(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
}
function from_candid_Assignment_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Assignment): Assignment {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    title: string;
    subject: string;
    owner: Principal;
    createdAt: _Time;
    dueDate: _Time;
    updatedAt: _Time;
    notes: [] | [string];
    priority: _Priority;
}): {
    id: bigint;
    status: Status;
    title: string;
    subject: string;
    owner: Principal;
    createdAt: Time;
    dueDate: Time;
    updatedAt: Time;
    notes?: string;
    priority: Priority;
} {
    return {
        id: value.id,
        status: from_candid_Status_n11(_uploadFile, _downloadFile, value.status),
        title: value.title,
        subject: value.subject,
        owner: value.owner,
        createdAt: value.createdAt,
        dueDate: value.dueDate,
        updatedAt: value.updatedAt,
        notes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.notes)),
        priority: from_candid_Priority_n14(_uploadFile, _downloadFile, value.priority)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): Status {
    return "pending" in value ? Status.pending : "completed" in value ? Status.completed : "inProgress" in value ? Status.inProgress : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "medium" in value ? Priority.medium : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Status>): Array<Status> {
    return value.map((x)=>from_candid_Status_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Assignment>): Array<Assignment> {
    return value.map((x)=>from_candid_Assignment_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Priority_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Priority.low ? {
        low: null
    } : value == Priority.high ? {
        high: null
    } : value == Priority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == Status.pending ? {
        pending: null
    } : value == Status.completed ? {
        completed: null
    } : value == Status.inProgress ? {
        inProgress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
